### ISSUE TITLE
Is it possible to support multiple languages?

### ISSUE THREAD

**Issue by yyoossk** [tallbl0nde/TriPlayer#17]
I want to translate it into Japanese

**Comment by tallbl0nde** [comment]
I'm planning to add support for other languages, however I need to first find a font that supports essentially every character and then edit the code to read the text in from other files. I'll ping you here once I've done that!

**Comment by yyoossk** [comment]
thx!
It seems that this font is compatible with all languages
https://github.com/XorTroll/Goldleaf/pull/500/commits/76e2020bc5a9f3d0365e6732a622c4f5dfcc479b

**Comment by provomeister** [comment]
I'm willing to provide a french translation when we get there 🎉

**Comment by tallbl0nde** [comment]
Good news is I'm just about ready for translations - I just need to double check everything works properly and add an option in the settings! I may get it all done today :P

**Comment by tallbl0nde** [comment]
That was quicker than expected, everything is ready! All you need to do is make a copy of `Application/romfs/lang/en.json` and rename it to your language code, and translate the strings within the file. If you know your way around code, feel free to add the required code in order for it to appear in-app. Otherwise I can edit the code where needed after merging the translation.

I'll close this issue as it's now possible to support other languages, it's just a matter of waiting for translations :P

Thank you in advance! :)

**Comment by HookedBehemoth** [comment]
That code seems familiar.
Would you mind giving credit to the respective project?
Especially as licenses are compatible in this case.

**Comment by tallbl0nde** [comment]
Can do, apologies for not doing so. *I think* I was looking at Awoo Installer as a guide for how to do this language stuff, so how would you like to it to be credited?
