### ISSUE TITLE
Crash at start screen "Preparing your library"

### ISSUE THREAD

**Issue by clamintus** [tallbl0nde/TriPlayer#19]
When I start TriPlayer, it hangs when displaying "Preparing your library" and then crashes after some seconds with the usual Switch software error screen.
I checked the filenames in /music as advised in #18 but every song I have has an ASCII filename.
The overlay instead just says "Nothing to play".

**Comment by tallbl0nde** [comment]
I'm going to need more information, specifically the crash report found under `/atmosphere/crash_reports`. You'll have to look through them and find the one that has lines that include `(TriPlayer + 0x...)`

**Comment by clamintus** [comment]
[01604914312_0100152000022000.log](https://github.com/tallbl0nde/TriPlayer/files/5539958/01604914312_0100152000022000.log)

Okay like this?

**Comment by tallbl0nde** [comment]
That looks correct, I'll give it a look over soon and report back! :)

**Comment by tallbl0nde** [comment]
It looks to be an issue with the code that analyzes the .mp3's to calculate their length. I'm not sure what could be causing this, my guess is a corrupted mp3 (or perhaps my code does indeed have an issue). Unfortunately I can't tell you what song is causing the problem. The good news is there's plans to use a library to do this instead of my own code so this should be fixed in the next major release.

**Comment by clamintus** [comment]
Ahhhh I see, in fact there was a corrupted mp3 song I forgot there. Now it works! Sorry for the trouble. :)

**Comment by tallbl0nde** [comment]
No problem at all! Glad to hear it was an easy fix.
